# Triggers
# This pipeline will be trigger manually for releases
trigger: none
pr:
  autoCancel: false
  branches:
    include:
      - '*'
      -
# Regression tests are split to 4 jobs because of timeout 360 minutes on job
jobs:
  - template: 'templates/system_test_general.yaml'
    parameters:
      name: 'regression_kafka_mirrormaker'
      display_name: 'regression-bundle I. -  kafka + mirrormaker'
      test_case: 'kafka.*ST,mirrormaker.*ST'
      groups: 'regression'
      cluster_operator_install_type: 'bundle'
      timeout: 360

  - template: 'templates/system_test_general.yaml'
    parameters:
      name: 'regression_connect_security'
      display_name: 'regression-bundle II. - connect + security'
      test_case: 'connect.*ST,security.*ST'
      groups: 'regression'
      cluster_operator_install_type: 'bundle'
      timeout: 360

  - template: 'templates/system_test_general.yaml'
    parameters:
      name: 'regression_operators_rollingupdate_watcher'
      display_name: 'regression-bundle III. - operator + rollingupdate + watcher'
      test_case: 'operators.*ST,rollingupdate.*ST,watcher.*ST'
      groups: 'regression'
      cluster_operator_install_type: 'bundle'
      timeout: 360

  - template: 'templates/system_test_general.yaml'
    parameters:
      name: 'regression_all_remaining'
      display_name: 'regression-bundle IV. - remaining system tests'
      # !LoggingChangeST is skipped because it's kinda flaky o azure
      test_case: '!kafka.*ST,!mirrormaker.*ST,!connect.*ST,!security.*ST,!LoggingChangeST,!operators.*ST,!rollingupdate.*ST,!watcher.*ST'
      groups: 'regression'
      cluster_operator_install_type: 'bundle'
      timeout: 360
